development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "github_stats"
      threads: 2
      processes: 1
      polling_interval: 1
    - queues: "markdown_processing"
      threads: 1
      processes: 1
      polling_interval: 5
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

test:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "github_stats"
      threads: 2
      processes: 1
      polling_interval: 1
    - queues: "markdown_processing"
      threads: 1
      processes: 1
      polling_interval: 5
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "github_stats"
      threads: 2
      processes: 1
      polling_interval: 1
    - queues: "markdown_processing"
      threads: 1
      processes: 1
      polling_interval: 5
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
